// export const MASTER_COMMAND_LIST = [
//     { cmd_id: 0x01, name: 'CTRL_MOVE' },
//     { cmd_id: 0x02, name: 'CTRL_STOP' },
//     { cmd_id: 0x03, name: 'CTRL_MOVETO' },
//     { cmd_id: 0x04, name: 'CTRL_MOVEOF' },
//     { cmd_id: 0x05, name: 'CTRL_WINK' },
//     { cmd_id: 0x06, name: 'CTRL_NETWORK_LOCK' },
//     { cmd_id: 0x0C, name: 'GET_MOTOR_POSITION' },
//     { cmd_id: 0x0D, name: 'POST_MOTOR_POSITION' },
//     { cmd_id: 0x0E, name: 'GET_MOTOR_STATUS' },
//     { cmd_id: 0x0F, name: 'POST_MOTOR_STATUS' },
//     { cmd_id: 0x10, name: 'SET_APP_MODE' },
//     { cmd_id: 0x20, name: 'GET_APP_MODE' },
//     { cmd_id: 0x30, name: 'POST_APP_MODE' },
//     { cmd_id: 0x11, name: 'SET_MOTOR_LIMITS' },
//     { cmd_id: 0x21, name: 'GET_MOTOR_LIMITS' },
//     { cmd_id: 0x31, name: 'POST_MOTOR_LIMITS' },
//     { cmd_id: 0x12, name: 'SET_MOTOR_DIRECTION' },
//     { cmd_id: 0x22, name: 'GET_MOTOR_DIRECTION' },
//     { cmd_id: 0x32, name: 'POST_MOTOR_DIRECTION' },
//     { cmd_id: 0x13, name: 'SET_MOTOR_ROLLING_SPEED' },
//     { cmd_id: 0x23, name: 'GET_MOTOR_ROLLING_SPEED' },
//     { cmd_id: 0x33, name: 'POST_MOTOR_ROLLING_SPEED' },
//     { cmd_id: 0x14, name: 'SET_MOTOR_TILTING_SPEED' },
//     { cmd_id: 0x24, name: 'GET_MOTOR_TILTING_SPEED' },
//     { cmd_id: 0x34, name: 'POST_MOTOR_TILTING_SPEED' },
//     { cmd_id: 0x15, name: 'SET_MOTOR_IP' },
//     { cmd_id: 0x25, name: 'GET_MOTOR_IP' },
//     { cmd_id: 0x35, name: 'POST_MOTOR_IP' },
//     { cmd_id: 0x16, name: 'SET_NETWORK_LOCK' },
//     { cmd_id: 0x26, name: 'GET_NETWORK_LOCK' },
//     { cmd_id: 0x36, name: 'POST_NETWORK_LOCK' },
//     { cmd_id: 0x17, name: 'SET_LOCAL_UI' },
//     { cmd_id: 0x27, name: 'GET_LOCAL_UI' },
//     { cmd_id: 0x37, name: 'POST_LOCAL_UI' },
//     { cmd_id: 0x18, name: 'SET_TILT_LIMITS' },
//     { cmd_id: 0x28, name: 'GET_TILT_LIMITS' },
//     { cmd_id: 0x38, name: 'POST_TILT_LIMITS' },
//     { cmd_id: 0x1F, name: 'SET_FACTORY_DEFAULT' },
//     { cmd_id: 0x2F, name: 'GET_FACTORY_DEFAULT' },
//     { cmd_id: 0x3F, name: 'POST_FACTORY_DEFAULT' },
//     { cmd_id: 0x50, name: 'SET_NODE_DISCOVERY' },
//     { cmd_id: 0x40, name: 'GET_NODE_ADDR' },
//     { cmd_id: 0x60, name: 'POST_NODE_ADDR' },
//     { cmd_id: 0x51, name: 'SET_GROUP_ADDR' },
//     { cmd_id: 0x41, name: 'GET_GROUP_ADDR' },
//     { cmd_id: 0x61, name: 'POST_GROUP_ADDR' },
//     { cmd_id: 0x55, name: 'SET_NODE_LABEL' },
//     { cmd_id: 0x45, name: 'GET_NODE_LABEL' },
//     { cmd_id: 0x65, name: 'POST_NODE_LABEL' },
//     { cmd_id: 0x56, name: 'SET_NETWORK_CONFIG' },
//     { cmd_id: 0x46, name: 'GET_NETWORK_CONFIG' },
//     { cmd_id: 0x66, name: 'POST_NETWORK_CONFIG' },
//     { cmd_id: 0x4C, name: 'GET_NODE_SERIAL_NUMBER' },
//     { cmd_id: 0x6C, name: 'POST_NODE_SERIAL_NUMBER' },
//     { cmd_id: 0x4D, name: 'GET_NETWORK_ERROR_STAT' },
//     { cmd_id: 0x6D, name: 'POST_NETWORK_ERROR_STAT' },
//     { cmd_id: 0x5E, name: 'SET_NETWORK_STAT' },
//     { cmd_id: 0x4E, name: 'GET_NETWORK_STAT' },
//     { cmd_id: 0x6E, name: 'POST_NETWORK_STAT' },
//     { cmd_id: 0x7F, name: 'ACK' },
//     { cmd_id: 0x6F, name: 'nACK' },
//     { cmd_id: 0x70, name: 'GET_NODE_STACK_VERSION' },
//     { cmd_id: 0x71, name: 'POST_NODE_STACK_VERSION' },
//     { cmd_id: 0x74, name: 'GET_NODE_APP_VERSION' },
//     { cmd_id: 0x75, name: 'POST_NODE_APP_VERSION' },
//     { cmd_id: 0x90, name: 'SET_SWITCH_ADDRESS' },
//     { cmd_id: 0x80, name: 'GET_SWITCH_ADDRESS' },
//     { cmd_id: 0xA0, name: 'POST_SWITCH_ADDRESS' },
//     { cmd_id: 0x92, name: 'SET_SWITCH_SETTINGS' },
//     { cmd_id: 0x82, name: 'GET_SWITCH_SETTINGS' },
//     { cmd_id: 0xA2, name: 'POST_SWITCH_SETTING' },
//     { cmd_id: 0x93, name: 'SET_INDIVIDUAL_SWITCH_GROUPS' },
//     { cmd_id: 0x83, name: 'GET_INDIVIDUAL_SWITCH_GROUPS' },
//     { cmd_id: 0xA3, name: 'POST_INDIVIDUAL_SWITCH_GROUPS' },
//     { cmd_id: 0x8F, name: 'GET_FIRMWARE_VERSION' },
//     { cmd_id: 0x9F, name: 'POST_FIRMWARE_VERSION' },
//     { cmd_id: 0x81, name: 'GET_KEYPAD_TYPE' }, // Command description not in DOCS - Duplicate command
//     { cmd_id: 0x94, name: 'SET_KEYPAD_TYPE' }, // Command description not in DOCS
//     { cmd_id: 0xA1, name: 'POST_KEYPAD_TYPE' }, // Command description not in DOCS - Duplicate command
//     { cmd_id: 0xB0, name: 'DIAG_GET_TOTAL_MOVE_COUNT' },
//     { cmd_id: 0xB1, name: 'DIAG_GET_TOTAL_REV_COUNT' },
//     { cmd_id: 0xB2, name: 'DIAG_GET_THERMAL_COUNT' },
//     { cmd_id: 0xB3, name: 'DIAG_GET_OBSTACLE_COUNT' },
//     { cmd_id: 0xB4, name: 'DIAG_GET_POWER_COUNT' },
//     { cmd_id: 0xB5, name: 'DIAG_GET_RESET_COUNT' },
//     { cmd_id: 0xB6, name: 'DIAG_GET_ENCODER_ERRORS' },
//     { cmd_id: 0xFF, name: 'UNKNOWN_COMMAND' },
//     { cmd_id: 0x39, name: 'POST_MOTOR_SOFT_START_STOP' },
//     { cmd_id: 0x29, name: 'GET_MOTOR_SOFT_START_STOP' },
//     { cmd_id: 0x19, name: 'SET_MOTOR_SOFT_START_STOP' },
//     { cmd_id: 0xA7, name: 'POST_CHANNEL_STATUS' }, // Command description not in DOCS
//     { cmd_id: 0xB7, name: 'GET_CHANNEL_STATUS' }, // Command description not in DOCS
//     { cmd_id: 0x87, name: 'CONTROL_CHANNEL' }, // Command description not in DOCS
//     { cmd_id: 0x80, name: 'SET_CALIBRATION' },
//     { cmd_id: 0x1A, name: 'SET_TORQUE_LIMITATION' }, // Command description not in DOCS
//     { cmd_id: 0x2A, name: 'GET_TORQUE_LIMITATION' },// Command description not in DOCS
//     { cmd_id: 0x3A, name: 'POST_TORQUE_LIMITATION' }, // Command description not in DOCS
//     { cmd_id: 0x80, name: 'SET_DCT_MODE' },
//     { cmd_id: 0x90, name: 'GET_DCT_MODE' },
//     { cmd_id: 0xA0, name: 'POST_DCT_MODE' },
//     { cmd_id: 0x81, name: 'SET_TOUCH_MOTION_SENSITIVITY' },
//     { cmd_id: 0x91, name: 'GET_TOUCH_MOTION_SENSITIVITY' },
//     { cmd_id: 0xA1, name: 'POST_TOUCH_MOTION_SENSITIVITY' },
//     { cmd_id: 0x82, name: 'SET_START_AUTO_LIMITS_SEEK' },
// ];

// export const CMD = {
//     CTRL_MOVE: 0x01,
//     CTRL_STOP: 0x02,
//     CTRL_MOVETO: 0x03,
//     CTRL_MOVEOF: 0x04,
//     CTRL_WINK: 0x05,
//     CTRL_NETWORK_LOCK: 0x06,
//     GET_MOTOR_POSITION: 0x0C,
//     POST_MOTOR_POSITION: 0x0D,
//     GET_MOTOR_STATUS: 0x0E,
//     POST_MOTOR_STATUS: 0x0F,
//     SET_APP_MODE: 0x10,
//     GET_APP_MODE: 0x20,
//     POST_APP_MODE: 0x30,
//     SET_MOTOR_LIMITS: 0x11,
//     GET_MOTOR_LIMITS: 0x21,
//     POST_MOTOR_LIMITS: 0x31,
//     SET_MOTOR_DIRECTION: 0x12,
//     GET_MOTOR_DIRECTION: 0x22,
//     POST_MOTOR_DIRECTION: 0x32,
//     SET_MOTOR_ROLLING_SPEED: 0x13,
//     GET_MOTOR_ROLLING_SPEED: 0x23,
//     POST_MOTOR_ROLLING_SPEED: 0x33,
//     SET_MOTOR_TILTING_SPEED: 0x14,
//     GET_MOTOR_TILTING_SPEED: 0x24,
//     POST_MOTOR_TILTING_SPEED: 0x34,
//     SET_MOTOR_IP: 0x15,
//     GET_MOTOR_IP: 0x25,
//     POST_MOTOR_IP: 0x35,
//     SET_NETWORK_LOCK: 0x16,
//     GET_NETWORK_LOCK: 0x26,
//     POST_NETWORK_LOCK: 0x36,
//     SET_LOCAL_UI: 0x17,
//     GET_LOCAL_UI: 0x27,
//     POST_LOCAL_UI: 0x37,
//     SET_TILT_LIMITS: 0x18,
//     GET_TILT_LIMITS: 0x28,
//     POST_TILT_LIMITS: 0x38,
//     SET_FACTORY_DEFAULT: 0x1F,
//     GET_FACTORY_DEFAULT: 0x2F,
//     POST_FACTORY_DEFAULT: 0x3F,
//     SET_NODE_DISCOVERY: 0x50,
//     GET_NODE_ADDR: 0x40,
//     POST_NODE_ADDR: 0x60,
//     SET_GROUP_ADDR: 0x51,
//     GET_GROUP_ADDR: 0x41,
//     POST_GROUP_ADDR: 0x61,
//     SET_NODE_LABEL: 0x55,
//     GET_NODE_LABEL: 0x45,
//     POST_NODE_LABEL: 0x65,
//     SET_NETWORK_CONFIG: 0x56,
//     GET_NETWORK_CONFIG: 0x46,
//     POST_NETWORK_CONFIG: 0x66,
//     GET_NODE_SERIAL_NUMBER: 0x4C,
//     POST_NODE_SERIAL_NUMBER: 0x6C,
//     GET_NETWORK_ERROR_STAT: 0x4D,
//     POST_NETWORK_ERROR_STAT: 0x6D,
//     SET_NETWORK_STAT: 0x5E,
//     GET_NETWORK_STAT: 0x4E,
//     POST_NETWORK_STAT: 0x6E,
//     ACK: 0x7F,
//     nACK: 0x6F,
//     GET_NODE_STACK_VERSION: 0x70,
//     POST_NODE_STACK_VERSION: 0x71,
//     GET_NODE_APP_VERSION: 0x74,
//     POST_NODE_APP_VERSION: 0x75,
//     SET_SWITCH_ADDRESS: 0x90,
//     GET_SWITCH_ADDRESS: 0x80,
//     POST_SWITCH_ADDRESS: 0xA0,
//     SET_SWITCH_SETTINGS: 0x92,
//     GET_SWITCH_SETTINGS: 0x82,
//     POST_SWITCH_SETTING: 0xA2,
//     SET_INDIVIDUAL_SWITCH_GROUPS: 0x93,
//     GET_INDIVIDUAL_SWITCH_GROUPS: 0x83,
//     POST_INDIVIDUAL_SWITCH_GROUPS: 0xA3,
//     GET_FIRMWARE_VERSION: 0x8F,
//     POST_FIRMWARE_VERSION: 0x9F,
//     GET_KEYPAD_TYPE: 0x81,
//     SET_KEYPAD_TYPE: 0x94,
//     POST_KEYPAD_TYPE: 0xA1,
//     DIAG_GET_TOTAL_MOVE_COUNT: 0xB0,
//     DIAG_GET_TOTAL_REV_COUNT: 0xB1,
//     DIAG_GET_THERMAL_COUNT: 0xB2,
//     DIAG_GET_OBSTACLE_COUNT: 0xB3,
//     DIAG_GET_POWER_COUNT: 0xB4,
//     DIAG_GET_RESET_COUNT: 0xB5,
//     DIAG_GET_ENCODER_ERRORS: 0xB6,
//     UNKNOWN_COMMAND: 0xFF,
//     POST_MOTOR_SOFT_START_STOP: 0x39,
//     GET_MOTOR_SOFT_START_STOP: 0x29,
//     SET_MOTOR_SOFT_START_STOP: 0x19,
//     POST_CHANNEL_STATUS: 0xA7,
//     GET_CHANNEL_STATUS: 0xB7,
//     CONTROL_CHANNEL: 0x87,
//     SET_CALIBRATION: 0x80,
//     SET_TORQUE_LIMITATION: 0x1A,
//     GET_TORQUE_LIMITATION: 0x2A,
//     POST_TORQUE_LIMITATION: 0x3A,
//     SET_DCT_MODE: 0x80,
//     GET_DCT_MODE: 0x90,
//     POST_DCT_MODE: 0xA0,
//     SET_TOUCH_MOTION_SENSITIVITY: 0x81,
//     GET_TOUCH_MOTION_SENSITIVITY: 0x91,
//     POST_TOUCH_MOTION_SENSITIVITY: 0xA1,
//     SET_START_AUTO_LIMITS_SEEK: 0x82,
// };

export const NODE_TYPE = [
	{
		node_type: 0x06,
		sub_node_type: 5039367,
		builder_method: 'Glydea_FrameBuilder',
		parser_method: 'Glydea_DataParser',
		CMD_ARRAY: 'ALL_COMMANDS',
	},
	{
		node_type: 0x09,
		sub_node_type: 5132734,
		builder_method: 'LSU40_FrameBuilder',
		parser_method: 'LSU40_DataParser',
		CMD_ARRAY: 'ALL_COMMANDS',
	},
	{
		node_type: 0x07,
		sub_node_type: 5071757,
		builder_method: 'LSU50_FrameBuilder',
		parser_method: 'LSU50_DataParser',
		CMD_ARRAY: 'ALL_COMMANDS',
	},
	{
		node_type: 0x02,
		sub_node_type: 5063313,
		builder_method: 'ST30_FrameBuilder',
		parser_method: 'ST30_DataParser',
		CMD_ARRAY: 'ALL_COMMANDS',
	},
	{
		node_type: 0x02,
		sub_node_type: 5157730,
		builder_method: 'QT30_FrameBuilder',
		parser_method: 'QT30_DataParser',
		CMD_ARRAY: 'ALL_COMMANDS',
	},
	{
		node_type: 0x0a,
		sub_node_type: null,
		builder_method: 'ST40_FrameBuilder',
		parser_method: 'ST40_DataParser',
		CMD_ARRAY: 'ALL_COMMANDS',
	},
	{
		node_type: 0x08,
		sub_node_type: 5123276,
		builder_method: 'ST50_FrameBuilder',
		parser_method: 'ST50_DataParser',
		CMD_ARRAY: 'ALL_COMMANDS',
	},
	{
		node_type: 0x0e,
		sub_node_type: null,
		builder_method: 'Generic_Keypad_FrameBuilder',
		parser_method: 'Generic_Keypad_DataParser',
		CMD_ARRAY: 'KEYPAD_METHOD_LIST',
	},
	{
		node_type: 0x0f,
		sub_node_type: null,
		builder_method: 'WSC11_FrameBuilder',
		parser_method: 'WSC11_DataParser',
		CMD_ARRAY: 'WSC11_SENSOR_METHOD_LIST',
	},
	{
		node_type: 0x05,
		sub_node_type: null,
		builder_method: 'Generic_Transmiter_FrameBuilder',
		parser_method: 'Generic_Transmiter_DataParser',
		CMD_ARRAY: 'TRANSMITER_METHOD_LIST',
	},
	{
		node_type: 0x0d,
		sub_node_type: null,
		builder_method: 'Generic_Receiver_FrameBuilder',
		parser_method: 'Generic_Receiver_DataParser',
		CMD_ARRAY: 'RECEIVER_METHOD_LIST',
	}
];

export const DEFAULT_NODE_TYPE = {
	node_type: 0x00,
	builder_method: 'Generic_FrameBuilder',
	parser_method: 'Generic_DataParser',
	CMD_ARRAY: 'GENERIC_MOTOR_METHOD_LIST',
};
