import {
  ChevronDown,
  ChevronUp,
  List,
  Play,
  RefreshCw,
  Save,
  Trash2,
} from "lucide-react";
import { useDeviceConfig } from "~/hooks/useDeviceConfig";
import MotorActionIcon from "./motorControl/MotorActionIcon";
import MotorGoToPosition from "./motorControl/MotorGoToPosition";
import { useEffect, useState } from "react";
import { useMotors } from "~/hooks/useMotors";
import LoaderComponent from "~/components/sharedComponent/LoaderComponent";
import { lstNodeType } from "~/constant/constant";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "~/components/ui/dialog";
import { Button } from "~/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";
import { SetProButton } from "~/components/sharedComponent/setProButton";
import { MotorIP } from "./motorControl/MotorIP";
import MotorStepToMovement from "./motorControl/MotorStepToMovement";
import { toast } from "sonner";
import { useComport } from "~/hooks/useComport";

function MotorIpPosition() {
  const { isOfflineEditMode, isComportConnected } = useComport();
  const { motorActionDisabled } = useDeviceConfig();
  const {
    selectedMotor,
    selectedMotorId,
    motorIPLoading,
    fetchMotorIpByIdThunk,
    moveMotorOfFunctionThunk,
    setMotorIpThunk,
    moveMotorToPositionThunk,
    eraseAllMotorIpsThunk,
    autoGenerateMotorIpsThunk,
  } = useMotors();
  const [currentIPIndex, setCurrentIPIndex] = useState<number | null>(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);
  const [confirmType, setConfirmType] = useState<"single" | "all" | null>(null);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [selectedIpCount, setSelectedIpCount] = useState<string>("16");
  const motorType = lstNodeType.find(
    (motor) => motor.node_id === selectedMotor?.model_no
  )?.node_type_name;

  useEffect(() => {
    if (!isComportConnected || isOfflineEditMode || !selectedMotorId) return;

    if (selectedMotor?.tbl_motor.ip_data == null) {
      fetchMotorIpByIdThunk(selectedMotorId!, true);
    }
  }, [])

  const handleNextIpUp = () => {
    // Logic to go to the next IP up
    moveMotorOfFunctionThunk({
      device_id: selectedMotorId!,
      function_type: "ip_up",
      isACK: true,
    });
  };

  const handleNextIpDown = () => {
    // Logic to go to the next IP down
    moveMotorOfFunctionThunk({
      device_id: selectedMotorId!,
      function_type: "ip_down",
      isACK: true,
    });
  };

  const handleAutoGenerateIPs = () => {
    setShowAutoGenerateDialog(true);
  };

  const handleAutoGenerateSubmit = () => {
    if (selectedMotorId && selectedIpCount) {
      autoGenerateMotorIpsThunk({
        device_id: selectedMotorId,
        ip_count: parseInt(selectedIpCount, 10),
      });
      setShowAutoGenerateDialog(false);
      setSelectedIpCount("");
    }
  };

  const handleMotorIPRefresh = () => {
    // Logic to refresh motor IPs
    if (selectedMotorId) {
      fetchMotorIpByIdThunk(selectedMotorId, true);
    }
  };

  const handleDeleteAllMotorIPs = () => {
    // Logic to delete all motor IPs
    eraseAllMotorIpsThunk(selectedMotorId!);
  };

  const handleCurrentIPAsCurrentPositionSet = () => {
    setMotorIpThunk({
      device_id: selectedMotorId!,
      function_type: "curr_pos",
      ip_index: currentIPIndex!,
    });
  };

  const handleIPSet = (value_position: number) => {
    if (value_position <= 0) return toast.error("Position must be greater than 0");
    // Logic to set motor to specific IP
    setMotorIpThunk({
      device_id: selectedMotorId!,
      function_type: "pos_pulse",
      ip_index: currentIPIndex!,
      value_position: value_position,
    });
  };

  const handleEraseIp = () => {
    setMotorIpThunk({
      device_id: selectedMotorId!,
      function_type: "delete",
      ip_index: currentIPIndex!, // 0 or any value indicating all IPs
    });
  };

  const goToIpPosition = () => {
    if (!selectedMotorId || currentIPIndex == null) return;
    const existingIp = selectedMotor?.tbl_motor.ip_data?.find(
      (ip) => ip.index === currentIPIndex
    );
    if (!existingIp || existingIp.pulse == null) {
      return toast.error(`IP${currentIPIndex} is not set.`);
    }
    moveMotorToPositionThunk({
      device_id: selectedMotorId,
      function_type: "ip",
      isACK: true,
      value_position: currentIPIndex,
    });

  }

  return (
    <div className="relative w-full h-full flex flex-col justify-start gap-10 p-4">
      <div className="w-full flex justify-between items-center">
        <div className="flex justify-start items-center gap-4">
          <span className="text-textDarkColor">Go to IP: </span>
          <div className="flex justify-center items-center gap-3">
            <MotorActionIcon
              disabled={motorActionDisabled}
              Icon={ChevronUp}
              tooltip="Next IP Up"
              onClick={handleNextIpUp}
            />
            <MotorActionIcon
              disabled={motorActionDisabled}
              Icon={ChevronDown}
              tooltip="Next IP Down"
              onClick={handleNextIpDown}
            />
          </div>
        </div>

        <div className="flex justify-center items-center gap-4">
          <button
            disabled={motorActionDisabled || motorType === "Glydea"}
            onClick={handleAutoGenerateIPs}
            className="flex justify-center items-center gap-2 bg-buttonColor px-6 py-2 rounded-full disabled:opacity-50"
          >
            <List size={16} className="text-white" />
            <span className="text-white text-sm">Auto Generate IPs</span>
          </button>
          <MotorActionIcon
            Icon={RefreshCw}
            tooltip="Refresh"
            disabled={motorActionDisabled || isOfflineEditMode}
            onClick={handleMotorIPRefresh}
            className="border-none bg-buttonColor"
            iconClassName="text-white"
          />
          <MotorActionIcon
            Icon={Trash2}
            tooltip="Erase All IPs"
            disabled={motorActionDisabled}
            onClick={() => {
              if (motorActionDisabled) return;
              setConfirmType("all");
              setShowConfirmDialog(true);
            }}
            className="border-none bg-deleteButtonColor"
            iconClassName="text-white"
            iconFill="white"
          />
        </div>
      </div>

      <div className="w-full flex flex-col justify-center items-center gap-10">
        <MotorIP setCurrentIPIndex={setCurrentIPIndex} currentIPIndex={currentIPIndex} />
        <div className="flex flex-row flex-wrap h-fit max-h-[280px] justify-center items-center gap-4">
          <MotorStepToMovement />
          <MotorGoToPosition
            title={`Enter value for IP${currentIPIndex !== null ? `${currentIPIndex}` : ""}`}
            from="motor_ip_position"
            showIpButtons
            onIpButtonClick={handleIPSet}
            showBottomText={false}
            disabled={motorActionDisabled || currentIPIndex === null}
            currentIpIndex={currentIPIndex}
          // ipValuePercentage={
          //   currentIPIndex !== null
          //     ? selectedMotor?.tbl_motor?.ip_data?.[
          //       currentIPIndex - 1
          //     ]?.percentage?.toString() || ""
          //     : ""
          // }
          // ipValuePosition={
          //   currentIPIndex !== null
          //     ? selectedMotor?.tbl_motor?.ip_data?.[
          //       currentIPIndex - 1
          //     ]?.pulse?.toString() || ""
          //     : ""
          // }
          />
          <div className="flex flex-col justify-center items-center gap-4">
            <SetProButton
              onClick={goToIpPosition}
              type="submit"
              disabled={motorActionDisabled || !currentIPIndex || isOfflineEditMode}
            >
              <Play size={14} className="text-white" fill="white" />
              <span className="text-sm text-white">
                Go to IP{currentIPIndex !== null ? `${currentIPIndex}` : ""}
              </span>
            </SetProButton>
            <SetProButton
              type="submit"
              disabled={motorActionDisabled || !currentIPIndex || isOfflineEditMode}
              onClick={handleCurrentIPAsCurrentPositionSet}
            >
              <Save size={14} className="text-white" />
              <span className="text-sm text-white">
                Set IP{currentIPIndex !== null ? `${currentIPIndex}` : ""} at
                Current
              </span>
            </SetProButton>
            <button
              disabled={motorActionDisabled || !currentIPIndex}
              onClick={() => {
                if (motorActionDisabled || !currentIPIndex) return;
                setConfirmType("single");
                setShowConfirmDialog(true);
              }}
              className="flex justify-center items-center gap-2 rounded-full px-6 py-2 bg-deleteButtonColor disabled:opacity-50"
            >
              <Trash2 size={14} className="text-white" fill="white" />
              <span className="text-sm text-white">
                Erase IP{currentIPIndex !== null ? `${currentIPIndex}` : ""}
              </span>
            </button>
          </div>
        </div>
      </div>

      <Dialog open={showConfirmDialog} onOpenChange={setShowConfirmDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {confirmType === "all" ? "Erase All IPs" : "Erase This IP?"}
            </DialogTitle>

            <DialogDescription>
              {confirmType === "all"
                ? "Are you sure you want to erase all IP positions? This action cannot be undone."
                : `Are you sure you want to erase IP${currentIPIndex}? This action cannot be undone.`}
            </DialogDescription>
          </DialogHeader>

          <DialogFooter>
            <SetProButton
              buttonType="cancel"
              onClick={() => setShowConfirmDialog(false)}
              className="rounded-full"
            >
              Cancel
            </SetProButton>

            <SetProButton
              buttonType="submit"
              onClick={() => {
                if (confirmType === "all") {
                  handleDeleteAllMotorIPs();
                } else if (confirmType === "single") {
                  handleEraseIp();
                }
                setShowConfirmDialog(false);
              }}
              className="rounded-full bg-deleteButtonColor text-white hover:bg-deleteButtonColor/90"
            >
              Confirm
            </SetProButton>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog
        open={showAutoGenerateDialog}
        onOpenChange={setShowAutoGenerateDialog}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Auto Generate IPs</DialogTitle>
            <DialogDescription>
              Select the number of IPs to auto-generate for this motor.
            </DialogDescription>
          </DialogHeader>

          <div className="py-4">
            <Select value={selectedIpCount} onValueChange={setSelectedIpCount}>
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select IP count" />
              </SelectTrigger>
              <SelectContent>
                {Array.from({ length: 16 }, (_, i) => i + 1).map((num) => (
                  <SelectItem key={num} value={num.toString()}>
                    {num}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowAutoGenerateDialog(false);
                setSelectedIpCount("");
              }}
              className="rounded-full"
            >
              Cancel
            </Button>
            <Button
              onClick={handleAutoGenerateSubmit}
              disabled={!selectedIpCount}
              className="rounded-full bg-buttonColor text-white hover:bg-buttonColor/90"
            >
              Submit
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {motorIPLoading && (
        <div className="absolute inset-0 w-full h-full bg-slate-100/80 flex flex-col gap-4 justify-center items-center">
          <LoaderComponent size={50} className="text-buttonColor" />
          <span className="text-buttonColor">Fetching Motor IPs...</span>
        </div>
      )}
    </div>
  );
}

export default MotorIpPosition;
